//Burger Builder actions

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";


//Order actions
export const PURCHASE_BURGUER_START = "PURCHASE_BURGUER_START";
export const PURCHASE_BURGUER_SUCCESS = "PURCHASE_BURGUER_SUCCESS";
export const PURCHASE_BURGUER_FAIL = "PURCHASE_BURGUER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";


export const FETCH_ORDERS_PENDING = "FETCH_ORDERS_PENDING";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";


// Auth
export const AUTH_USER = "AUTH_USER";
export const AUTH_PENDING = "AUTH_PENDING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITItATE_LOGOUT = "AUTH_INITItATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";